# -*- coding: utf-8 -*-
"""Python project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pq6axxC3CfZt_OEEy--fdE5yIdLOlME5
"""

#Data loading and cleaning using pandas
#read_csv(filepath,seperator=",")
import pandas as pd
df=pd.read_csv('CrimesOnWomenData.csv',delimiter=',')  #loading the data
df.info()

df.value_counts()

duplicates = df[df.duplicated()]
print(duplicates)

# To find null values
df.isna().sum()

# Drop unnecessary index column
if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'])

# Handle missing values
df.fillna(0, inplace=True)

# Standardize state names
df['State'] = df['State'].str.strip().str.upper()

# Summary Statistics
# ========================
print("\nBasic Info:")
print(df.info())

print("\nSummary Statistics:")
print(df.describe())

# Total crimes per year
df['Total_Crimes'] = df.iloc[:, 2:].sum(axis=1)
yearly_trend = df.groupby('Year')['Total_Crimes'].sum()

# Year-on-Year Growth Rate
yearly_growth = yearly_trend.pct_change() * 100

# Total crimes per state
statewise_crimes = df.groupby('State')['Total_Crimes'].sum().sort_values(ascending=False)

# Pivot for Heatmap
pivot_table = df.pivot_table(values='Total_Crimes', index='State', columns='Year', aggfunc='sum').fillna(0)

# Visualizations
# ========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid", palette="pastel")


# --- Crimes trend over years ---
plt.figure(figsize=(10,6))
plt.plot(yearly_trend.index, yearly_trend.values, marker='o', linewidth=2)
plt.title("Total Crimes Against Women Over Years", fontsize=14)
plt.xlabel("Year")
plt.ylabel("Number of Crimes")
plt.grid(True)
plt.show()

# --- Year-on-Year Growth ---
plt.figure(figsize=(10,6))
plt.plot(yearly_growth.index, yearly_growth.values, marker='o', color='purple')
plt.title("Year-on-Year Growth in Crimes (%)", fontsize=14)
plt.xlabel("Year")
plt.ylabel("Growth Rate (%)")
plt.axhline(0, color='red', linestyle='--')
plt.grid(True)
plt.show()

# --- Top 10 states by total crimes ---
plt.figure(figsize=(12,6))
sns.barplot(x=statewise_crimes.head(10).values, y=statewise_crimes.head(10).index, palette="Reds_r")
plt.title("Top 10 States with Highest Crimes Against Women", fontsize=14)
plt.xlabel("Total Crimes")
plt.ylabel("State")
plt.show()

# bottom 5 states
bottom5_states = statewise_crimes.tail(5).index
plt.figure(figsize=(12,6))

sns.barplot(x=statewise_crimes.tail(5).values, y=bottom5_states, palette="Greens_r")
plt.title("Bottom 5 States with Lowest Crimes Against Women", fontsize=14)
plt.xlabel("Total Crimes")
plt.ylabel("State")
plt.show()

# --- Correlation Heatmap ---
plt.figure(figsize=(10,6))
sns.heatmap(df.iloc[:,2:-1].corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Between Different Crimes", fontsize=14)
plt.show()

# --- Pie Chart for Crime Distribution (Nationwide Total) ---
crime_totals = df.iloc[:,2:-1].sum()
plt.figure(figsize=(8,8))
plt.pie(crime_totals, labels=crime_totals.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette("pastel"))
plt.title("Distribution of Crime Types Against Women", fontsize=14)
plt.show()

# --- Heatmap (State vs Year) ---
plt.figure(figsize=(12,8))
sns.heatmap(pivot_table, cmap="Reds", linewidths=.5)
plt.title("State vs Year Heatmap of Crimes Against Women", fontsize=14)
plt.xlabel("Year")
plt.ylabel("State")
plt.show()
# Year with highest crimes
year_max = yearly_trend.idxmax()
print(f"\nYear with highest total crimes: {year_max} ({yearly_trend.max()} cases)")

# State with highest crimes
state_max = statewise_crimes.idxmax()
print(f"State with highest crimes overall: {state_max} ({statewise_crimes.max()} cases)")

# Crime type trend over years
plt.figure(figsize=(12,6))
for col in df.columns[2:-1]:
    plt.plot(df.groupby('Year')[col].sum(), marker='o', label=col)
plt.title("Trend of Different Crime Types Over Years", fontsize=14)
plt.xlabel("Year")
plt.ylabel("Number of Cases")
plt.legend()
plt.show()

#Crimes by Region (Group States)
region_map = {
    "DELHI": "NORTH", "PUNJAB": "NORTH", "HARYANA": "NORTH",
    "KERALA": "SOUTH", "TAMIL NADU": "SOUTH", "KARNATAKA": "SOUTH",
    "WEST BENGAL": "EAST", "ODISHA": "EAST", "BIHAR": "EAST",
    "RAJASTHAN": "WEST", "GUJARAT": "WEST", "MAHARASHTRA": "WEST",
    "MADHYA PRADESH": "CENTRAL", "CHHATTISGARH": "CENTRAL",
    "ASSAM": "NORTH-EAST", "MANIPUR": "NORTH-EAST"
}
df['Region'] = df['State'].map(region_map)

region_trend = df.groupby(['Year','Region'])['Total_Crimes'].sum().unstack()

region_trend.plot(figsize=(12,6), marker='o')
plt.title("Crimes Trend by Region", fontsize=14)
plt.xlabel("Year")
plt.ylabel("Crimes")
plt.legend(title="Region")
plt.show()

'''Key Insights:
1.Crimes against women have shown a steady rise over the years.

2.Uttar Pradesh, Maharashtra, and West Bengal record the highest cases.

3.Smaller states and UTs like Sikkim and Nagaland report the lowest cases.

4.Cruelty by husband and relatives forms the largest share of crimes.

5.Assault against modesty is the second most common reported crime.

6.Northern and central regions contribute the highest crime rates.
'''



